### ISSUE TITLE
Issues Port Forwarding

### ISSUE THREAD

**Issue by Ne-Chan** [adtitas/ngrok-rdp#25]
Can i ask a question: How to open port forwarding?

**Comment by adtitas** [comment]
These might help - 
https://tryrdp.com/blog/port-forwarding-on-windows-vps/
https://www.dynu.com/Resources/Tutorials/DynamicDNS/RemoteDesktop

**Comment by Ne-Chan** [comment]
![image](https://user-images.githubusercontent.com/120474294/209436569-b19910d9-f799-413d-bfef-09a0e25e7832.png)
It's didn't work. I try open 3389 but not open
