### ISSUE TITLE
how about add CloudFlare Tunnel support or use CloudFlare Tunnel to replace ngrok ?

### ISSUE THREAD

**Issue by y7rr** [adtitas/ngrok-rdp#7]
[CloudFlare Tunnel](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup) is faster and more friendly

**Comment by adtitas** [comment]
Cloudflare Zero Trust service is probably paid. But you can try if you can afford and see how it differs from the ngrok.
