### ISSUE TITLE
Cloudflare Zero Trust is free even without credit card

### ISSUE THREAD

**Issue by 1w5** [adtitas/ngrok-rdp#8]
[[Cloudflare Zero Trust service is probably paid. But you can try if you can afford and see how it differs from the ngrok.](https://github.com/adtitas/ngrok-rdp/issues/7#issuecomment-1219572938)](https://github.com/adtitas/ngrok-rdp/issues/7#issuecomment-1219572938)

**Comment by adtitas** [comment]
Then, you can try instead of ngrok.
